services:
  # Backend API Service
  - type: web
    name: pos-backend
    env: node
    plan: starter
    buildCommand: cd packages/backend && npm install
    startCommand: cd packages/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    
  # Frontend Option A: Static Site (Recommended)
  - type: web
    name: pos-frontend-static
    env: static
    buildCommand: cd packages/frontend && npm install && npm run build
    staticPublishPath: packages/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  
  # Frontend Option B: Web Service (Alternative - comment out Option A if using this)
  # - type: web
  #   name: pos-frontend-web
  #   env: node
  #   plan: starter
  #   buildCommand: cd packages/frontend && npm install && npm run build
  #   startCommand: cd packages/frontend && npm start
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: PORT
  #       sync: false
